export const GET_PLANETS_REQUEST = 'GET_PLANETS_REQUEST'
export const GET_PLANETS_SUCCESS = 'GET_PLANETS_SUCCESS'
export const GET_PLANETS_ERROR = 'GET_PLANETS_ERROR'

export const GET_FILMS_REQUEST = 'GET_FILMS_REQUEST'
export const GET_FILMS_SUCCESS = 'GET_FILMS_SUCCESS'
export const GET_FILMS_ERROR = 'GET_FILMS_ERROR'

export const GET_PEOPLES_REQUEST = 'GET_PEOPLES_REQUEST'
export const GET_PEOPLES_SUCCESS = 'GET_PEOPLES_SUCCESS'
export const GET_PEOPLES_ERROR = 'GET_PEOPLES_ERROR'
